#!/bin/bash

# Add an "alert" alias for long running commands.  Use like so: sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# custom
alias art='php artisan'
alias cm='cmatrix -absC cyan -u 1'

# dir
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

# some more ls aliases
alias ls='ls --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias lisa='ls -lisa'

# tmux
alias tm='tmux -2'
alias tc='tm new -s'
alias ta='tm a'
alias tl='tm ls'

# aptitude
alias au='sudo apt update'
alias as='aptitude search'
alias ai='sudo apt install'
alias ag='sudo apt upgrade'
alias ad='sudo apt dist-upgrade'

# git
alias gg='git status' ## deal with it xD
alias ga='git add .'
alias gaf='git add * --all -f'
alias gc='git commit -a'
alias gp='git push'
alias gr='git reset --hard'
alias gd='git diff'
alias gds='git diff --staged'

alias mnt='sshfs -o idmap=user -o follow_symlinks -o workaround=rename'

# chrome fix for HiRes 4k Displays
alias chrome="chromium-browser --force-device-scale-factor=2"

# color man pages
man() {
    env \
        LESS_TERMCAP_mb=$(printf "\e[1;31m") \
        LESS_TERMCAP_md=$(printf "\e[1;31m") \
        LESS_TERMCAP_me=$(printf "\e[0m") \
        LESS_TERMCAP_se=$(printf "\e[0m") \
        LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
        LESS_TERMCAP_ue=$(printf "\e[0m") \
        LESS_TERMCAP_us=$(printf "\e[1;32m") \
            man "$@"
}

# alias for colored grep
alias grep='grep --color=always'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
coloredgrep() {
    grep -n -r $1 $2 | less -R
}
alias gl=coloredgrep


