##[
 Script: buildModules
 ----------------

 This script will generate neccessary files to import all Modules in the Installer

 Creates: **importModules.nim**::
   MODULES.add([MODULENAME])
   import "[MODULEPATH]"

 Creates: **installModules.nim**::
   discard [MODULENAME].install( DotfileModuleAttributes( user: USER, path: PATH, home: HOME, pwd: PWD ) )

 :Author: **LimeBlack ~ David Crimi**
 :Useful:
   `Installer <installer.html>`_
   `importModules <importModules.html>`_
   `installModules <installModules.html>`_

]##

import re  ## TODO limit this import
from times import format, getTime, getLocalTime
from os import walkFiles

let DEBUG: bool = false
var importDocString: string = """##[

 AutoGenerated: importModules
 -----------------------------

 Autogenerated Script to import all Modules

 :Author: **LimeBlack ~ David Crimi**
 :GeneratedBy: `buildModules <buildModules.html>`_
"""
var installDocString: string = """##[

 AutoGenerated: installModules
 -----------------------------

 Autogenerated script to install all Modules

 :Author: **LimeBlack ~ David Crimi**
 :GeneratedBy: `buildModules <buildModules.html>`_
"""
let timestamp: string = format( getLocalTime(getTime()), "yyyy-MM-dd'_'HH:mm" )
importDocString = importDocString & " :Timestamp: " & timestamp & "\n" & "]##" & "\n"
installDocString = installDocString & " :Timestamp: " & timestamp & "\n" & "]##" & "\n"

when isMainModule:

  var MODULES: seq[ string ] = @[] # hold list of available modules

  var argumentString: string = "user: USER, path: PATH, home: HOME, pwd: PWD, arch: ARCH, dist: DIST, pkg_mng: PKG_MNG, silent: SILENT, force: FORCE"
  var installContent: string

  let importFile  = open("importModules.nim",  fmWrite)
  let installFile = open("installModules.nim", fmWrite)

  # create: import file
  importFile.write( importDocString )
  for file in walkFiles("modules/*.nim"):
    let moduleName: string = replacef(file, re"modules/*([a-zA-Z0-9]*).nim$", "$1")
    MODULES.add( moduleName )
    importFile.write("MODULES.add(\"" & moduleName & "\")\n")
    importFile.write("import " & file[0..^5] & "\n\n")

  importFile.close

  # create: installModules.nim
  installFile.write( installDocString )
  for module in MODULES:
    installContent = "discard " & module & ".install(DotfileModuleAttributes(" & argumentString & "))"
    if DEBUG:
      echo "Will add to installModules.nim: " & installContent
    installFile.write( installContent & "\n" )

  installFile.close
