nim doc ./testEnvironment.nim
nim doc ./libraries/inception/inception.nim
nim doc ./libraries/spinner/testSpinner.nim
nim doc ./libraries/spinner/spinner.nim
nim doc ./libraries/dotfileTypes.nim
nim doc ./libraries/dotfile.nim
nim doc ./libraries/philanthrop.nim
nim doc ./libraries/arnold/arnold.nim
nim doc ./libraries/models/User.nim
nim doc ./buildEnvironment.nim
nim doc ./buildModules.nim
nim doc ./installModules.nim
nim doc ./installer.nim
nim doc ./modules/M20OpenSSH.nim
nim doc ./modules/M50Vim.nim
nim doc ./modules/M01Init.nim
nim doc ./modules/M50Wine.nim
nim doc ./modules/M50mPad.nim
nim doc ./modules/M05Dotfiles.nim
nim doc ./modules/M20Git.nim
nim doc ./importModules.nim
