##[

 AutoGenerated: importModules
 -----------------------------

 Autogenerated Script to import all Modules

 :Author: **LimeBlack ~ David Crimi**
 :GeneratedBy: `buildModules <buildModules.html>`_
 :Timestamp: 2017-05-30_17:13
]##
MODULES.add("M01Init")
import modules/M01Init

MODULES.add("M05Dotfiles")
import modules/M05Dotfiles

MODULES.add("M20Git")
import modules/M20Git

MODULES.add("M20OpenSSH")
import modules/M20OpenSSH

MODULES.add("M50Vim")
import modules/M50Vim

MODULES.add("M50Wine")
import modules/M50Wine

MODULES.add("M50mPad")
import modules/M50mPad

