discard M01Init.install(DotfileModuleAttributes(user: USER, path: PATH, home: HOME, pwd: PWD, arch: ARCH, dist: DIST, silent: SILENT, force: FORCE))
discard M05Dotfiles.install(DotfileModuleAttributes(user: USER, path: PATH, home: HOME, pwd: PWD, arch: ARCH, dist: DIST, silent: SILENT, force: FORCE))
discard M20Git.install(DotfileModuleAttributes(user: USER, path: PATH, home: HOME, pwd: PWD, arch: ARCH, dist: DIST, silent: SILENT, force: FORCE))
discard M20OpenSSH.install(DotfileModuleAttributes(user: USER, path: PATH, home: HOME, pwd: PWD, arch: ARCH, dist: DIST, silent: SILENT, force: FORCE))
discard M50Vim.install(DotfileModuleAttributes(user: USER, path: PATH, home: HOME, pwd: PWD, arch: ARCH, dist: DIST, silent: SILENT, force: FORCE))
discard M50Wine.install(DotfileModuleAttributes(user: USER, path: PATH, home: HOME, pwd: PWD, arch: ARCH, dist: DIST, silent: SILENT, force: FORCE))
discard M50mPad.install(DotfileModuleAttributes(user: USER, path: PATH, home: HOME, pwd: PWD, arch: ARCH, dist: DIST, silent: SILENT, force: FORCE))
